apiVersion: v1
kind: PersistentVolume
metadata:
  name: slurm-local-pv
  namespace: jhub-no-cull
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lustre-local-storage
  local:
    path: /lustre
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - b5r13u15
